"""
Documentation Structure Templates.

Defines the folder structure and templates for AI-friendly documentation.
Based on best practices for contextual documentation that helps AI coding assistants.
"""

from dataclasses import dataclass, field
from typing import Optional
from enum import Enum


class DocCategory(Enum):
    """Categories of documentation for different purposes."""
    CHARTS = "charts"           # Visual diagrams (Mermaid)
    CONTEXT = "context"         # Reference documentation
    USAGE = "usage"            # Practical guides
    IMPLEMENTATIONS = "implementations"  # Implementation history


@dataclass
class DocTemplate:
    """Template for a single documentation file."""
    filename: str
    title: str
    description: str
    category: DocCategory
    content_template: str
    order: int = 0
    required: bool = True


# =====================================================
# BASE DOCUMENTATION STRUCTURE
# =====================================================

FOLDER_STRUCTURE = """
docs/
├── charts/                      # 📊 Visual diagrams and documentation
│   ├── 00_INDEX.md             # Index and navigation for diagrams
│   ├── 01_ARCHITECTURE_OVERVIEW.md
│   ├── 02_CLASS_DIAGRAM.md
│   ├── 03_SEQUENCE_FLOWS.md
│   ├── 04_COMPONENT_DIAGRAM.md
│   ├── 05_DATA_FLOW.md
│   └── 06_DEPENDENCY_GRAPH.md
│
├── context/                     # 📚 Reference documentation
│   ├── ARCHITECTURE.md         # Architectural patterns and decisions
│   ├── COMPONENTS.md           # Component/module catalog
│   ├── PATTERNS.md             # Code patterns used
│   └── TECH_STACK.md           # Technology stack and dependencies
│
├── usage/                       # 📖 Practical guides
│   ├── 00_INDEX.md             # Decision tree for navigation
│   ├── 01_GETTING_STARTED.md   # Setup and first steps
│   ├── 02_CODE_PATTERNS.md     # How to write code in this project
│   ├── 03_DATA_FLOW.md         # How data flows
│   └── 04_ADDING_FEATURES.md   # How to add new features
│
├── implementations/             # 📝 Implementation history
│   └── [FEATURE_NAME].md       # Doc for each implemented feature
│
└── AGENT_RULES.md               # 🤖 Rules for AI agents
"""


# =====================================================
# DOCUMENTATION TEMPLATES
# =====================================================

CHARTS_INDEX_TEMPLATE = """# 📊 Visual Documentation - {project_name}

> Diagrams and visual documentation for global project context.

## 📁 Document Structure

| # | Document | Description |
|---|----------|-------------|
| 01 | [System Architecture](./01_ARCHITECTURE_OVERVIEW.md) | Architecture overview, tech stack and structure |
| 02 | [Class Diagram](./02_CLASS_DIAGRAM.md) | Domain model with main entities |
| 03 | [Flows and Sequences](./03_SEQUENCE_FLOWS.md) | Main operation flows |
| 04 | [Components](./04_COMPONENT_DIAGRAM.md) | Component and module hierarchy |
| 05 | [Data Flow](./05_DATA_FLOW.md) | How data flows through the system |
| 06 | [Dependency Graph](./06_DEPENDENCY_GRAPH.md) | Dependencies between modules |

---

## 🎯 How to Use This Documentation

### For New Developers
1. Start with [01_ARCHITECTURE_OVERVIEW](./01_ARCHITECTURE_OVERVIEW.md)
2. Read [02_CLASS_DIAGRAM](./02_CLASS_DIAGRAM.md) to understand entities
3. Explore [04_COMPONENT_DIAGRAM](./04_COMPONENT_DIAGRAM.md) to understand structure

### For Implementing New Features
1. Check [04_COMPONENT_DIAGRAM](./04_COMPONENT_DIAGRAM.md) for patterns
2. See [05_DATA_FLOW](./05_DATA_FLOW.md) to understand the flow
3. Use [03_SEQUENCE_FLOWS](./03_SEQUENCE_FLOWS.md) as reference

### For Debug and Maintenance
1. [06_DEPENDENCY_GRAPH](./06_DEPENDENCY_GRAPH.md) to understand dependencies
2. [05_DATA_FLOW](./05_DATA_FLOW.md) to trace issues

---

## 🏗️ Quick Overview

### Main Stack
```
{tech_stack_summary}
```

### Main Entities
```
{entities_summary}
```

### Data Flow
```
{data_flow_summary}
```

---

*Last updated: {date}*
"""


ARCHITECTURE_OVERVIEW_TEMPLATE = """# System Architecture - {project_name}

## Architecture Overview

```mermaid
{architecture_diagram}
```

## Application Layers

```mermaid
{layers_diagram}
```

## Technology Stack

| Layer | Technology | Purpose |
|-------|------------|---------|
{tech_stack_table}

## Directory Structure

```
{directory_structure}
```

## Architectural Principles

{architecture_principles}

---

*Generated by Code Analysis Agent*
"""


CLASS_DIAGRAM_TEMPLATE = """# Class Diagram - {project_name}

## Domain Model

```mermaid
classDiagram
{class_diagram}
```

## Entity Descriptions

{entities_description}

## Relationships

{relationships_description}

---

*Generated by Code Analysis Agent*
"""


SEQUENCE_FLOWS_TEMPLATE = """# Flows and Sequences - {project_name}

## Main Flows

{main_flows}

## Sequence Diagrams

{sequence_diagrams}

---

*Generated by Code Analysis Agent*
"""


COMPONENT_DIAGRAM_TEMPLATE = """# Component Diagram - {project_name}

## Component Hierarchy

```mermaid
{component_hierarchy}
```

## Main Components

{components_description}

## Composition Patterns

{composition_patterns}

---

*Generated by Code Analysis Agent*
"""


DATA_FLOW_TEMPLATE = """# Data Flow - {project_name}

## Flow Diagram

```mermaid
{data_flow_diagram}
```

## Flow Description

{flow_description}

## Entry and Exit Points

{entry_exit_points}

---

*Generated by Code Analysis Agent*
"""


DEPENDENCY_GRAPH_TEMPLATE = """# Dependency Graph - {project_name}

## Overview

```mermaid
{dependency_diagram}
```

## Statistics

{dependency_stats}

## Most Important Modules

{important_modules}

## Potential Issues

{potential_issues}

---

*Generated by Code Analysis Agent*
"""


# =====================================================
# CONTEXT TEMPLATES
# =====================================================

ARCHITECTURE_CONTEXT_TEMPLATE = """# Architectural Context - {project_name}

> Quick reference guide about the project architecture.

**Architectural Pattern:** {architecture_pattern}
**Last Updated:** {date}

---

## 📋 Index

- [Architectural Decisions](#architectural-decisions)
- [Patterns Used](#patterns-used)
- [Code Conventions](#code-conventions)
- [Boundaries and Responsibilities](#boundaries-and-responsibilities)

---

## Architectural Decisions

{architectural_decisions}

## Patterns Used

{patterns_used}

## Code Conventions

{code_conventions}

## Boundaries and Responsibilities

{layer_responsibilities}

---

*Generated by Code Analysis Agent*
"""


COMPONENTS_CONTEXT_TEMPLATE = """# Component Catalog - {project_name}

> Complete documentation of system components/modules.

**Total components:** {component_count}
**Last Updated:** {date}

---

## 📋 Index

{index}

---

{components_documentation}

---

*Generated by Code Analysis Agent*
"""


PATTERNS_CONTEXT_TEMPLATE = """# Code Patterns - {project_name}

> Catalog of design patterns and conventions used in the project.

---

## 📋 Index

{index}

---

{patterns_documentation}

---

## When to Use Each Pattern

{pattern_usage_guide}

---

*Generated by Code Analysis Agent*
"""


TECH_STACK_TEMPLATE = """# Technology Stack - {project_name}

> Documentation of project technologies and dependencies.

---

## Main Stack

{main_stack}

## Dependencies

### Production
{production_deps}

### Development
{dev_deps}

## Versions and Compatibility

{version_compatibility}

---

*Generated by Code Analysis Agent*
"""


# =====================================================
# USAGE TEMPLATES
# =====================================================

USAGE_INDEX_TEMPLATE = """# Usage Index - {project_name}

> Decision tree to navigate the project documentation. Start here.

---

## Quick Decision Tree

**What do you need to do?**
```
START HERE
    │
    ├─► Starting on the project?
    │       │
    │       └─► 01_GETTING_STARTED.md
    │
    ├─► Writing code?
    │       │
    │       ├─► New component/module ──────► 02_CODE_PATTERNS.md
    │       └─► Understand data flow ──────► 03_DATA_FLOW.md
    │
    ├─► Adding features?
    │       │
    │       └─► 04_ADDING_FEATURES.md
    │
    └─► Understanding architecture?
            │
            └─► See `/charts/00_INDEX.md` for diagrams
```

---

## Guide Summary

| # | Guide | When to Use |
|---|-------|-------------|
| 01 | GETTING_STARTED | First time on the project |
| 02 | CODE_PATTERNS | Writing code following patterns |
| 03 | DATA_FLOW | Understanding how data flows |
| 04 | ADDING_FEATURES | Adding new features |

---

## Reference Documents

For quick reference when guides point to them:
```
/context/
├── ARCHITECTURE.md      ← Architectural decisions
├── COMPONENTS.md        ← Component catalog
├── PATTERNS.md          ← Code patterns
└── TECH_STACK.md        ← Technology stack
```

---

## Rules for AI Agents

1. **Read this INDEX first** - don't load all guides
2. **Follow one path** - load only the guide matching the task
3. **Reference docs on demand** - only when the guide points to them
4. **Historical context last** - check `/implementations/` only if needed

---

*Last updated: {date}*
"""


GETTING_STARTED_TEMPLATE = """# Guide: Getting Started - {project_name}

> Step by step to setup and understand the project.

---

## Prerequisites

{prerequisites}

## Environment Setup

{setup_steps}

## Project Structure

{project_structure}

## First Steps

{first_steps}

## Useful Commands

{useful_commands}

---

*Back to [Index](./00_INDEX.md)*
"""


CODE_PATTERNS_TEMPLATE = """# Guide: Code Patterns - {project_name}

> How to write code following project patterns.

---

## Required Documents

Before writing code, check:

| Document | Path | Why |
|----------|------|-----|
{required_docs_table}

---

## Creation Checklist

{creation_checklist}

## Style Patterns

{style_patterns}

## Examples by Type

{examples_by_type}

---

*Back to [Index](./00_INDEX.md)*
"""


DATA_FLOW_GUIDE_TEMPLATE = """# Guide: Data Flow - {project_name}

> How data flows through the system.

---

## Flow Overview

{flow_overview}

## Entry Points

{entry_points}

## Data Transformations

{data_transformations}

## State and Cache

{state_management}

---

*Back to [Index](./00_INDEX.md)*
"""


ADDING_FEATURES_TEMPLATE = """# Guide: Adding Features - {project_name}

> Step by step to add new features.

---

## Before Starting

{before_starting}

## Step by Step

{step_by_step}

## Final Checklist

{final_checklist}

## Examples of Added Features

{feature_examples}

---

*Back to [Index](./00_INDEX.md)*
"""


# =====================================================
# AGENT RULES TEMPLATE
# =====================================================

AGENT_RULES_TEMPLATE = """# 🤖 Rules for AI Agents - {project_name}

> Specific guidelines for AI agents working with this codebase.

---

## Project Context

{project_context}

## Fundamental Rules

### 1. Documentation Navigation

```
ALWAYS start by reading:
1. This file (AGENT_RULES.md)
2. /docs/usage/00_INDEX.md to understand which guide to follow
3. Load ONLY the documents needed for the task
```

### 2. File Structure

{file_structure_rules}

### 3. Code Patterns

{code_pattern_rules}

### 4. Naming Conventions

{naming_conventions}

### 5. Dependencies and Imports

{import_rules}

---

## Useful Commands

{useful_commands}

---

## Anti-Patterns (What NOT to do)

{anti_patterns}

---

## Checklist Before Committing

{commit_checklist}

---

*Generated by Code Analysis Agent*
*Last updated: {date}*
"""


@dataclass
class DocumentationStructure:
    """
    Complete documentation structure for a project.
    
    This class organizes all documentation templates and provides
    methods to generate the full documentation set.
    """
    
    project_name: str
    architecture_pattern: str
    tech_stack: dict = field(default_factory=dict)
    patterns_detected: list = field(default_factory=list)
    components: list = field(default_factory=list)
    flows: list = field(default_factory=list)
    
    def get_folder_structure(self) -> str:
        """Return the recommended folder structure."""
        return FOLDER_STRUCTURE
    
    def get_all_templates(self) -> dict[DocCategory, list[DocTemplate]]:
        """Return all documentation templates organized by category."""
        return {
            DocCategory.CHARTS: [
                DocTemplate(
                    filename="00_INDEX.md",
                    title="Diagram Index",
                    description="Navigation for visual diagrams",
                    category=DocCategory.CHARTS,
                    content_template=CHARTS_INDEX_TEMPLATE,
                    order=0,
                ),
                DocTemplate(
                    filename="01_ARCHITECTURE_OVERVIEW.md",
                    title="Architecture Overview",
                    description="System architecture diagram",
                    category=DocCategory.CHARTS,
                    content_template=ARCHITECTURE_OVERVIEW_TEMPLATE,
                    order=1,
                ),
                DocTemplate(
                    filename="02_CLASS_DIAGRAM.md",
                    title="Class Diagram",
                    description="Domain model",
                    category=DocCategory.CHARTS,
                    content_template=CLASS_DIAGRAM_TEMPLATE,
                    order=2,
                ),
                DocTemplate(
                    filename="03_SEQUENCE_FLOWS.md",
                    title="Flows and Sequences",
                    description="Sequence diagrams",
                    category=DocCategory.CHARTS,
                    content_template=SEQUENCE_FLOWS_TEMPLATE,
                    order=3,
                ),
                DocTemplate(
                    filename="04_COMPONENT_DIAGRAM.md",
                    title="Component Diagram",
                    description="Component hierarchy",
                    category=DocCategory.CHARTS,
                    content_template=COMPONENT_DIAGRAM_TEMPLATE,
                    order=4,
                ),
                DocTemplate(
                    filename="05_DATA_FLOW.md",
                    title="Data Flow",
                    description="How data flows",
                    category=DocCategory.CHARTS,
                    content_template=DATA_FLOW_TEMPLATE,
                    order=5,
                ),
                DocTemplate(
                    filename="06_DEPENDENCY_GRAPH.md",
                    title="Dependency Graph",
                    description="Dependencies between modules",
                    category=DocCategory.CHARTS,
                    content_template=DEPENDENCY_GRAPH_TEMPLATE,
                    order=6,
                ),
            ],
            DocCategory.CONTEXT: [
                DocTemplate(
                    filename="ARCHITECTURE.md",
                    title="Architectural Context",
                    description="Architectural decisions and patterns",
                    category=DocCategory.CONTEXT,
                    content_template=ARCHITECTURE_CONTEXT_TEMPLATE,
                    order=0,
                ),
                DocTemplate(
                    filename="COMPONENTS.md",
                    title="Component Catalog",
                    description="Documentation of all components",
                    category=DocCategory.CONTEXT,
                    content_template=COMPONENTS_CONTEXT_TEMPLATE,
                    order=1,
                ),
                DocTemplate(
                    filename="PATTERNS.md",
                    title="Code Patterns",
                    description="Design patterns used",
                    category=DocCategory.CONTEXT,
                    content_template=PATTERNS_CONTEXT_TEMPLATE,
                    order=2,
                ),
                DocTemplate(
                    filename="TECH_STACK.md",
                    title="Technology Stack",
                    description="Technologies and dependencies",
                    category=DocCategory.CONTEXT,
                    content_template=TECH_STACK_TEMPLATE,
                    order=3,
                ),
            ],
            DocCategory.USAGE: [
                DocTemplate(
                    filename="00_INDEX.md",
                    title="Usage Index",
                    description="Decision tree for navigation",
                    category=DocCategory.USAGE,
                    content_template=USAGE_INDEX_TEMPLATE,
                    order=0,
                ),
                DocTemplate(
                    filename="01_GETTING_STARTED.md",
                    title="Getting Started",
                    description="Setup and first steps",
                    category=DocCategory.USAGE,
                    content_template=GETTING_STARTED_TEMPLATE,
                    order=1,
                ),
                DocTemplate(
                    filename="02_CODE_PATTERNS.md",
                    title="Code Patterns",
                    description="How to write code in this project",
                    category=DocCategory.USAGE,
                    content_template=CODE_PATTERNS_TEMPLATE,
                    order=2,
                ),
                DocTemplate(
                    filename="03_DATA_FLOW.md",
                    title="Data Flow",
                    description="How data flows",
                    category=DocCategory.USAGE,
                    content_template=DATA_FLOW_GUIDE_TEMPLATE,
                    order=3,
                ),
                DocTemplate(
                    filename="04_ADDING_FEATURES.md",
                    title="Adding Features",
                    description="How to add new features",
                    category=DocCategory.USAGE,
                    content_template=ADDING_FEATURES_TEMPLATE,
                    order=4,
                ),
            ],
        }
    
    def get_agent_rules_template(self) -> DocTemplate:
        """Return the agent rules template."""
        return DocTemplate(
            filename="AGENT_RULES.md",
            title="Rules for Agents",
            description="Guidelines for AI agents",
            category=DocCategory.CONTEXT,  # Root level
            content_template=AGENT_RULES_TEMPLATE,
            order=0,
            required=True,
        )
